name: 'Hugo to GH Pages'
author: 'chabad360'
description: 'GitHub Action for Building a Hugo Site and Pushing it to Github Pages'

inputs:
  githubToken:
    description: 'A Github Personal Access Token with Repo permissions'
    required: true

  cname:
    description: 'The custom domain name for your GH Pages Site'
    required: false

  branch:
    description: 'The branch to push the built site to'
    required: false
    default: 'gh-pages'

runs:
  using: 'docker'
  image: 'docker://chabad360/hugo:latest'
  args:
    - '--gc'
    - '--minify'
    - '--cleanDestinationDir'

branding:
  icon: 'upload-cloud'  
  color: 'red'