name: Docker Image CI

on:
  push:
    branches: 
      - master
  
  schedule:
    - cron: '1 1 * * 0'   

jobs:

  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag chabad360/hugo-gh-pages/hugo

      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: chabad360/hugo
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}