name: Docker Image CI

on:
  push:
    branches: 
      - master
  
  schedule:
    - cron: '30 1 * * *'   

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
 
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/chabad360/hugo-gh-pages

      - name: Login to Docker Hub
        run: docker login ghcr.io --username=${{ secrets.DOCKER_USER }} --password=${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish to Docker Registry
        run: docker push ghcr.io/chabad360/hugo-gh-pages
